/**
 * Utility to export AI-generated content into beautifully styled, standalone HTML files.
 */

const TAILWIND_CDN = '<script src="https://cdn.tailwindcss.com"></script>';
const GOOGLE_FONTS = '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Outfit:wght@500;700&display=swap" rel="stylesheet">';

const BASE_STYLES = `
  <style>
    body { font-family: 'Inter', sans-serif; background-color: #f8fafc; color: #1e293b; }
    h1, h2, h3 { font-family: 'Outfit', sans-serif; }
    .glass-card { background: rgba(255, 255, 255, 0.9); backdrop-filter: blur(10px); border: 1px solid rgba(226, 232, 240, 0.8); }
    @media print { .no-print { display: none; } }
  </style>
`;

export type ExportType = 'quiz' | 'notes' | 'lesson' | 'flashcards';

export function exportToHTML(type: ExportType, data: any, topic: string) {
    let content = '';

    if (type === 'quiz') {
        const questions = data.questions || data.quiz_questions || [];
        content = `
      <div class="max-w-4xl mx-auto py-12 px-6">
        <header class="mb-12 text-center">
          <h1 class="text-4xl font-bold text-slate-900 mb-2">${topic} Quiz</h1>
          <p class="text-slate-500">Interactive Self-Assessment Generated by CogniMentor</p>
        </header>

        <form id="quizForm" class="space-y-8">
          ${questions.map((q: any, i: number) => `
            <div class="glass-card p-8 rounded-3xl shadow-xl transition-all hover:shadow-2xl">
              <p class="text-lg font-bold text-slate-800 mb-6">
                <span class="text-blue-600 mr-2">Q${i + 1}.</span> ${q.question || q.q}
              </p>
              <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                ${(q.options || []).map((opt: string, oi: number) => `
                  <label class="relative flex items-center p-4 cursor-pointer rounded-2xl border-2 border-slate-100 hover:border-blue-200 hover:bg-blue-50 transition-all group">
                    <input type="radio" name="q${i}" value="${opt}" class="w-4 h-4 text-blue-600 focus:ring-blue-500 mr-3">
                    <span class="text-sm font-medium text-slate-700">${opt}</span>
                  </label>
                `).join('')}
              </div>
            </div>
          `).join('')}

          <div class="text-center py-8 no-print">
            <button type="button" onclick="checkResults()" class="bg-blue-600 text-white px-10 py-4 rounded-2xl font-bold text-lg hover:bg-blue-700 transition-all shadow-lg shadow-blue-200">
              Check My Answers
            </button>
          </div>
        </form>

        <div id="results" class="hidden mt-8 p-10 glass-card rounded-[2.5rem] border-2 border-emerald-100 text-center animate-fade-in">
           <h2 class="text-3xl font-bold text-slate-900 mb-2">Quiz Results</h2>
           <p id="scoreText" class="text-5xl font-black text-emerald-600 mb-4">0/5</p>
           <button onclick="window.print()" class="text-blue-600 font-bold hover:underline">Download/Print as PDF</button>
        </div>

        <script>
          const correctAnswers = ${JSON.stringify(questions.map((q: any) => q.correct_answer || q.answer))};
          
          function checkResults() {
            const form = document.getElementById('quizForm');
            const resultsDiv = document.getElementById('results');
            const scoreText = document.getElementById('scoreText');
            let score = 0;

            correctAnswers.forEach((ans, i) => {
              const selected = form.querySelector(\`input[name="q\${i}"]:checked\`);
              if (selected && selected.value === ans) {
                score++;
                selected.parentElement.classList.add('bg-emerald-50', 'border-emerald-500');
              } else if (selected) {
                selected.parentElement.classList.add('bg-red-50', 'border-red-500');
              }
            });

            scoreText.textContent = \`\${score} / \${correctAnswers.length}\`;
            resultsDiv.classList.remove('hidden');
            window.scrollTo({ top: resultsDiv.offsetTop, behavior: 'smooth' });
          }
        </script>
      </div>
    `;
    } else if (type === 'notes') {
        content = `
      <div class="max-w-4xl mx-auto py-12 px-6">
        <header class="mb-12 border-b pb-8">
          <h1 class="text-4xl font-extrabold text-slate-900">${data.title || topic}</h1>
          <p class="text-slate-500 mt-2 text-lg italic">${data.summary || ''}</p>
        </header>

        <div class="space-y-12">
          ${(data.sections || []).map((section: any) => `
            <section>
              <h2 class="text-2xl font-bold text-blue-600 mb-4 flex items-center gap-3">
                <span class="w-2 h-8 bg-blue-600 rounded-full"></span>
                ${section.subtopic}
              </h2>
              <div class="glass-card p-8 rounded-3xl">
                <p class="text-slate-700 leading-relaxed text-lg mb-6">${section.content}</p>
                <ul class="grid grid-cols-1 md:grid-cols-2 gap-4">
                  ${(section.key_points || []).map((point: string) => `
                    <li class="flex items-start gap-3 text-sm text-slate-600">
                      <svg class="w-5 h-5 text-blue-500 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>
                      ${point}
                    </li>
                  `).join('')}
                </ul>
              </div>
            </section>
          `).join('')}
        </div>
      </div>
    `;
    } else if (type === 'lesson') {
        content = `
      <div class="max-w-4xl mx-auto py-12 px-6">
        <div class="glass-card p-10 rounded-[3rem] mb-12 border-2 border-blue-50">
          <h1 class="text-4xl font-black text-slate-900 mb-4">Lesson Plan: ${topic}</h1>
          <div class="bg-blue-600 text-white px-6 py-4 rounded-2xl inline-block font-bold">
            Objective: ${data.objective}
          </div>
        </div>

        <div class="space-y-8 relative">
          <div class="absolute left-8 top-0 bottom-0 w-1 bg-slate-100 hidden md:block"></div>
          
          ${(data.phases || []).map((phase: any, i: number) => `
            <div class="relative pl-0 md:pl-20 mb-12">
              <div class="absolute left-6 top-0 w-6 h-6 bg-blue-600 rounded-full border-4 border-white shadow-lg hidden md:block z-10"></div>
              <div class="glass-card p-8 rounded-[2rem] hover:translate-x-2 transition-all">
                <div class="flex items-center justify-between mb-4">
                  <h3 class="text-xl font-bold text-slate-900">${phase.phase_name}</h3>
                  <span class="bg-slate-100 text-slate-600 px-4 py-1 rounded-full text-sm font-bold">${phase.duration_minutes} min</span>
                </div>
                <ul class="space-y-3">
                  ${(phase.activities || []).map((act: string) => `
                    <li class="flex items-center gap-3 text-slate-600">
                      <div class="w-1.5 h-1.5 bg-blue-400 rounded-full"></div>
                      ${act}
                    </li>
                  `).join('')}
                </ul>
              </div>
            </div>
          `).join('')}
        </div>
      </div>
    `;
    } else if (type === 'flashcards') {
        content = `
      <div class="max-w-4xl mx-auto py-12 px-6">
        <h1 class="text-3xl font-bold text-center mb-12">${topic} Flashcard Deck</h1>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
          ${(data.flashcards || []).map((fc: any, i: number) => `
            <div class="glass-card p-8 rounded-3xl border-2 border-slate-50 flex flex-col h-full">
              <div class="text-[10px] uppercase tracking-widest font-black text-blue-500 mb-4 italic">Flashcard #${i + 1}</div>
              <div class="flex-1">
                <p class="text-lg font-bold text-slate-800 mb-6">${fc.front}</p>
                <div class="p-6 bg-slate-50/50 rounded-2xl border border-dashed border-slate-200">
                   <p class="text-sm text-slate-600 italic leading-relaxed">${fc.back}</p>
                </div>
              </div>
            </div>
          `).join('')}
        </div>
      </div>
    `;
    }

    const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${topic} - CogniMentor Expert Export</title>
      ${GOOGLE_FONTS}
      ${TAILWIND_CDN}
      ${BASE_STYLES}
    </head>
    <body>
      ${content}
      <footer class="mt-20 py-12 border-t text-center text-slate-400 text-sm no-print">
        Generated with AI by <strong class="text-blue-500">CogniMentor</strong> Studio.<br/>
        Professional Educational Resources for Modern Learners.
      </footer>
    </body>
    </html>
  `;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${topic.toLowerCase().replace(/\\s+/g, '_')}_${type}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
